[package]
name = "ethnum-bench"
version = "0.0.0"
publish = false
edition = "2021"

[[bench]]
name = "num"
harness = false

[dependencies]
ethnum = { path = ".." }
criterion = "0.3"
primitive-types = { version = "0.11", optional = true }
